[package]
name = "graphene"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rustyline = "15.0.0"
unicode-normalization = "0.1.24"
unicode-segmentation = "1.12.0"
